//! Per-engine drivers and the install/check/uninstall dispatch table.

use super::*;

// ---------------------------------------------------------------------------
// OpenCode plugin
// ---------------------------------------------------------------------------

/// Render our OpenCode plugin. The `a` path is embedded as a JSON string
/// literal (valid JS), and the plugin shells out via argv — no shell
/// quoting issues — wrapped so hook failures never surface to the agent.
pub fn opencode_plugin_source(a_bin: &str) -> String {
    let a_json = serde_json::to_string(a_bin).unwrap_or_else(|_| "\"a\"".to_string());
    format!(
        r#"// aplexer state-report plugin (generated by `a init`).
//
// Reports agent lifecycle to `a state-report` so `a list`, `a status` and
// the attach status bar show semantic state (idle/waiting/working) instead
// of guessing from PTY output. Best-effort: failures never surface to the
// agent. Re-running `a init` refreshes this file; `a init --uninstall`
// removes it. Other plugins in this dir are untouched.
import child_process from "node:child_process";

const A = {a_json};

function report(state) {{
  try {{
    child_process.spawnSync(A, ["state-report", state], {{ stdio: "ignore" }});
  }} catch (e) {{
    // best-effort; never throw out of a plugin hook
  }}
}}

export const AplexerStateReport = async () => {{
  return {{
    event: async ({{ event }}) => {{
      if (event.type === "session.idle") {{
        report("idle");
      }} else if (event.type === "permission.asked") {{
        report("waiting");
      }} else if (event.type === "session.error") {{
        report("waiting");
      }} else if (event.type === "session.created") {{
        report("working");
      }}
    }},
  }};
}};
"#
    )
}

// ---------------------------------------------------------------------------
// Filesystem drivers
// ---------------------------------------------------------------------------

/// One engine's install/check/uninstall outcome. Serializable so `a init
/// --json` / `a init --check --json` are the machine contract PocketShell
/// automates against.
#[derive(Debug, Clone, Serialize)]
pub struct EngineInitStatus {
    pub engine: String,
    pub installed: bool,
    pub action: String,
    pub message: String,
    pub paths: Vec<String>,
}

// ---------------------------------------------------------------------------
// Per-engine drivers
// ---------------------------------------------------------------------------

/// One managed file's outcome: `(changed, message)`, or an error naming
/// the file. An empty message is dropped from the engine's summary.
type FileOutcome = Result<(bool, String)>;

fn named(path: &Path, outcome: FileOutcome) -> FileOutcome {
    outcome.map_err(|e| anyhow::anyhow!("{}: {e:#}", path.display()))
}

fn display_paths<P: AsRef<Path>>(paths: impl IntoIterator<Item = P>) -> Vec<String> {
    paths
        .into_iter()
        .map(|p| p.as_ref().display().to_string())
        .collect()
}

/// `(failed, changed, messages)` over an engine's file outcomes.
fn fold_outcomes(outcomes: Vec<FileOutcome>) -> (bool, bool, Vec<String>) {
    let mut failed = false;
    let mut changed = false;
    let mut messages = Vec::with_capacity(outcomes.len());
    for outcome in outcomes {
        match outcome {
            Ok((file_changed, message)) => {
                changed |= file_changed;
                messages.push(message);
            }
            Err(e) => {
                failed = true;
                messages.push(e.to_string());
            }
        }
    }
    (failed, changed, messages)
}

impl EngineInitStatus {
    fn new(
        engine: &str,
        installed: bool,
        action: &str,
        messages: Vec<String>,
        paths: Vec<String>,
    ) -> Self {
        Self {
            engine: engine.to_string(),
            installed,
            action: action.to_string(),
            message: messages
                .into_iter()
                .filter(|m| !m.is_empty())
                .collect::<Vec<_>>()
                .join("; "),
            paths,
        }
    }

    /// Install verdict: any error fails the engine; otherwise `installed`
    /// when any file changed, else `present`.
    fn installed(engine: &str, outcomes: Vec<FileOutcome>, paths: Vec<String>) -> Self {
        let (failed, changed, messages) = fold_outcomes(outcomes);
        let action = if failed {
            "error"
        } else if changed {
            "installed"
        } else {
            "present"
        };
        Self::new(engine, !failed, action, messages, paths)
    }

    /// Check verdict: installed only when every file reports present.
    fn checked(engine: &str, checks: Vec<(bool, String)>, paths: Vec<String>) -> Self {
        let installed = checks.iter().all(|(present, _)| *present);
        let action = if installed { "present" } else { "absent" };
        let messages = checks.into_iter().map(|(_, message)| message).collect();
        Self::new(engine, installed, action, messages, paths)
    }

    /// Uninstall verdict: `removed` when anything was taken out, `absent`
    /// when there was nothing of ours, `error` when a removal failed.
    fn uninstalled(engine: &str, outcomes: Vec<FileOutcome>, paths: Vec<String>) -> Self {
        let (failed, changed, messages) = fold_outcomes(outcomes);
        let action = if failed {
            "error"
        } else if changed {
            "removed"
        } else {
            "absent"
        };
        Self::new(engine, false, action, messages, paths)
    }
}

// Engines whose hooks merge into one or more shared JSON settings files.

fn install_nested_files(
    engine: &str,
    files: &[PathBuf],
    events: &[(&str, &str)],
    a_bin: &str,
) -> EngineInitStatus {
    let outcomes = files
        .iter()
        .map(|path| named(path, install_nested_file(path, events, a_bin)))
        .collect();
    EngineInitStatus::installed(engine, outcomes, display_paths(files))
}

fn check_nested_files(
    engine: &str,
    files: &[PathBuf],
    events: &[(&str, &str)],
) -> EngineInitStatus {
    let checks = files
        .iter()
        .map(|path| check_nested_file(path, events))
        .collect();
    EngineInitStatus::checked(engine, checks, display_paths(files))
}

fn uninstall_nested_files(engine: &str, files: &[PathBuf]) -> EngineInitStatus {
    let outcomes = files
        .iter()
        .map(|path| named(path, uninstall_nested_file(path)))
        .collect();
    EngineInitStatus::uninstalled(engine, outcomes, display_paths(files))
}

// Engines with one file that is entirely ours (grok's `aplexer.json` in a
// merged hooks dir, opencode's plugin): written whole, removed whole.

fn install_owned_file(engine: &str, path: &Path, text: Result<String>) -> EngineInitStatus {
    let outcome = text
        .and_then(|text| write_if_changed(path, &text))
        .map(|wrote| {
            let verb = if wrote {
                "wrote"
            } else {
                "already installed in"
            };
            (wrote, format!("{verb} {}", path.display()))
        });
    EngineInitStatus::installed(engine, vec![named(path, outcome)], display_paths([path]))
}

fn remove_owned_file(path: &Path) -> FileOutcome {
    match fs::remove_file(path) {
        Ok(()) => Ok((true, format!("removed {}", path.display()))),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            Ok((false, format!("{} not present", path.display())))
        }
        Err(e) => Err(e).with_context(|| format!("remove {}", path.display())),
    }
}

fn uninstall_owned_file(engine: &str, path: &Path) -> EngineInitStatus {
    EngineInitStatus::uninstalled(
        engine,
        vec![named(path, remove_owned_file(path))],
        display_paths([path]),
    )
}

// claude

fn install_claude(targets: &HookTargets, a_bin: &str) -> EngineInitStatus {
    install_nested_files("claude", &targets.claude_settings, &CLAUDE_EVENTS, a_bin)
}

fn check_claude(targets: &HookTargets) -> EngineInitStatus {
    check_nested_files("claude", &targets.claude_settings, &CLAUDE_EVENTS)
}

fn uninstall_claude(targets: &HookTargets) -> EngineInitStatus {
    uninstall_nested_files("claude", &targets.claude_settings)
}

// codex: `hooks.json` per home, plus the legacy `notify` in `config.toml`.
// `zcodex` shares CODEX_HOME, so it is covered by the same dirs.

const CODEX_NOTE: &str = " (covers zcodex via shared CODEX_HOME)";

fn codex_hooks_paths(targets: &HookTargets) -> Vec<PathBuf> {
    targets
        .codex_dirs
        .iter()
        .map(|dir| dir.join(CODEX_HOOKS_FILENAME))
        .collect()
}

/// Legacy notify: set only when the file exists and has no `notify` at
/// all, never clobbering a foreign program (which may be PocketShell's
/// handler or the user's own).
fn ensure_codex_notify_file(config_path: &Path, a_bin: &str) -> FileOutcome {
    if !config_path.exists() {
        return Ok((false, String::new()));
    }
    let text = fs::read_to_string(config_path)
        .with_context(|| format!("read {}", config_path.display()))?;
    if codex_notify_state(&text) != NotifyState::Absent {
        return Ok((false, String::new()));
    }
    let (new_text, _) = ensure_codex_notify(&text, a_bin);
    let wrote = write_if_changed(config_path, &new_text)?;
    let message = if wrote {
        format!("set notify in {}", config_path.display())
    } else {
        String::new()
    };
    Ok((wrote, message))
}

fn remove_codex_notify_file(config_path: &Path) -> FileOutcome {
    if !config_path.exists() {
        return Ok((false, String::new()));
    }
    let text = fs::read_to_string(config_path)
        .with_context(|| format!("read {}", config_path.display()))?;
    let (new_text, changed) = remove_codex_notify(&text);
    if !changed {
        return Ok((false, String::new()));
    }
    write_if_changed(config_path, &new_text)?;
    Ok((
        true,
        format!("removed notify from {}", config_path.display()),
    ))
}

fn install_codex(targets: &HookTargets, a_bin: &str) -> EngineInitStatus {
    let mut outcomes = Vec::new();
    let mut paths = Vec::new();
    for dir in &targets.codex_dirs {
        let hooks_path = dir.join(CODEX_HOOKS_FILENAME);
        let config_path = dir.join("config.toml");
        outcomes.push(named(
            &hooks_path,
            install_nested_file(&hooks_path, &CODEX_EVENTS, a_bin),
        ));
        outcomes.push(named(
            &config_path,
            ensure_codex_notify_file(&config_path, a_bin),
        ));
        paths.extend(display_paths([&hooks_path, &config_path]));
    }
    let mut status = EngineInitStatus::installed("codex", outcomes, paths);
    status.message += CODEX_NOTE;
    status
}

fn check_codex(targets: &HookTargets) -> EngineInitStatus {
    let mut status = check_nested_files("codex", &codex_hooks_paths(targets), &CODEX_EVENTS);
    status.message += CODEX_NOTE;
    status
}

fn uninstall_codex(targets: &HookTargets) -> EngineInitStatus {
    let mut outcomes = Vec::new();
    let mut paths = Vec::new();
    for dir in &targets.codex_dirs {
        let hooks_path = dir.join(CODEX_HOOKS_FILENAME);
        let config_path = dir.join("config.toml");
        outcomes.push(named(&hooks_path, uninstall_nested_file(&hooks_path)));
        outcomes.push(named(&config_path, remove_codex_notify_file(&config_path)));
        paths.extend(display_paths([&hooks_path, &config_path]));
    }
    EngineInitStatus::uninstalled("codex", outcomes, paths)
}

// grok

fn grok_hooks_path(targets: &HookTargets) -> PathBuf {
    targets.grok_dir.join("hooks").join(GROK_HOOKS_FILENAME)
}

fn install_grok(targets: &HookTargets, a_bin: &str) -> EngineInitStatus {
    // Owned file in a merged dir: no need to read anything else.
    let mut doc = Value::Object(Default::default());
    let text = merge_nested_hooks(&mut doc, &GROK_EVENTS, a_bin).and_then(|_| render_json(&doc));
    install_owned_file("grok", &grok_hooks_path(targets), text)
}

fn check_grok(targets: &HookTargets) -> EngineInitStatus {
    check_nested_files("grok", &[grok_hooks_path(targets)], &GROK_EVENTS)
}

fn uninstall_grok(targets: &HookTargets) -> EngineInitStatus {
    uninstall_owned_file("grok", &grok_hooks_path(targets))
}

// gemini

fn install_gemini(targets: &HookTargets, a_bin: &str) -> EngineInitStatus {
    install_nested_files(
        "gemini",
        std::slice::from_ref(&targets.gemini_settings),
        &GEMINI_EVENTS,
        a_bin,
    )
}

fn check_gemini(targets: &HookTargets) -> EngineInitStatus {
    check_nested_files(
        "gemini",
        std::slice::from_ref(&targets.gemini_settings),
        &GEMINI_EVENTS,
    )
}

fn uninstall_gemini(targets: &HookTargets) -> EngineInitStatus {
    uninstall_nested_files("gemini", std::slice::from_ref(&targets.gemini_settings))
}

// opencode

fn opencode_plugin_path(targets: &HookTargets) -> PathBuf {
    targets.opencode_plugin_dir.join(OPENCODE_PLUGIN_FILENAME)
}

fn install_opencode(targets: &HookTargets, a_bin: &str) -> EngineInitStatus {
    install_owned_file(
        "opencode",
        &opencode_plugin_path(targets),
        Ok(opencode_plugin_source(a_bin)),
    )
}

fn check_opencode(targets: &HookTargets) -> EngineInitStatus {
    let path = opencode_plugin_path(targets);
    let installed = fs::read_to_string(&path).is_ok_and(|text| text.contains("state-report"));
    let message = if installed {
        format!("plugin installed at {}", path.display())
    } else {
        format!("{} not present", path.display())
    };
    EngineInitStatus::checked(
        "opencode",
        vec![(installed, message)],
        display_paths([&path]),
    )
}

fn uninstall_opencode(targets: &HookTargets) -> EngineInitStatus {
    uninstall_owned_file("opencode", &opencode_plugin_path(targets))
}

// ---------------------------------------------------------------------------
// Engine selection + top-level drivers
// ---------------------------------------------------------------------------

pub(crate) struct EngineDriver {
    pub(crate) engine: &'static str,
    install: fn(&HookTargets, &str) -> EngineInitStatus,
    check: fn(&HookTargets) -> EngineInitStatus,
    uninstall: fn(&HookTargets) -> EngineInitStatus,
}

/// In `HOOK_ENGINES` order, which is also the order statuses are reported.
pub(crate) const ENGINE_DRIVERS: [EngineDriver; 5] = [
    EngineDriver {
        engine: "claude",
        install: install_claude,
        check: check_claude,
        uninstall: uninstall_claude,
    },
    EngineDriver {
        engine: "codex",
        install: install_codex,
        check: check_codex,
        uninstall: uninstall_codex,
    },
    EngineDriver {
        engine: "grok",
        install: install_grok,
        check: check_grok,
        uninstall: uninstall_grok,
    },
    EngineDriver {
        engine: "gemini",
        install: install_gemini,
        check: check_gemini,
        uninstall: uninstall_gemini,
    },
    EngineDriver {
        engine: "opencode",
        install: install_opencode,
        check: check_opencode,
        uninstall: uninstall_opencode,
    },
];

/// Normalise `--engine` for `a init`: `zcodex` rides the codex dirs, every
/// other id must be one of `HOOK_ENGINES`.
pub fn normalize_engine_filter(engine: &str) -> Result<&'static str> {
    match engine {
        "claude" => Ok("claude"),
        "codex" | "zcodex" => Ok("codex"),
        "grok" => Ok("grok"),
        "gemini" => Ok("gemini"),
        "opencode" => Ok("opencode"),
        other => anyhow::bail!(
            "unknown engine {other:?} for hook installation; expected one of claude, codex, zcodex, grok, gemini, opencode"
        ),
    }
}

fn selected_drivers(engine: Option<&str>) -> impl Iterator<Item = &'static EngineDriver> + '_ {
    ENGINE_DRIVERS
        .iter()
        .filter(move |driver| engine.is_none_or(|want| want == driver.engine))
}

/// Install hooks for the selected engines. Idempotent; merge, never
/// clobber (see the module docs).
pub fn install(targets: &HookTargets, a_bin: &str, engine: Option<&str>) -> Vec<EngineInitStatus> {
    selected_drivers(engine)
        .map(|driver| (driver.install)(targets, a_bin))
        .collect()
}

/// Check hook presence for the selected engines. No files are touched.
pub fn check(targets: &HookTargets, engine: Option<&str>) -> Vec<EngineInitStatus> {
    selected_drivers(engine)
        .map(|driver| (driver.check)(targets))
        .collect()
}

/// Remove our hooks for the selected engines. Only `state-report` entries
/// and our own generated files are removed.
pub fn uninstall(targets: &HookTargets, engine: Option<&str>) -> Vec<EngineInitStatus> {
    selected_drivers(engine)
        .map(|driver| (driver.uninstall)(targets))
        .collect()
}
